"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = http://localhost
  name = oneorzero

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'oneorzero'
    langs = {
        'en': 'localhost',
    }

    def scriptpath(self, code):
        return {
            'en': '',
        }[code]

    def protocol(self, code):
        return {
            'en': 'http',
        }[code]
